services:
  mysql:
    image: mysql:8.4
    container_name: edusim-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edusim
    ports:
      - "3306:3306"
    volumes:
      - edusim_mysql_data:/var/lib/mysql

volumes:
  edusim_mysql_data:
